<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-45LN54O" failures="2" tests="2" name="Default test" time="21.337" errors="0" timestamp="2021-05-18T11:25:30 IST">
  <testcase classname="com.cucumber.testrunner.CustomAbstractTestNGCucumberTests" name="runScenario" time="8.175">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.cucumber.stepdefinition.Login.user_in_on_the_login_page(Login.java:34)
at ✽.user in on the login page(file:///D:/Java_FrameworkCreation_Workspace/cucumberframework/Feature/login.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cucumber.testrunner.CustomAbstractTestNGCucumberTests" name="runScenario" time="6.383">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.cucumber.stepdefinition.Login.user_in_on_the_login_page(Login.java:34)
at ✽.user in on the login page(file:///D:/Java_FrameworkCreation_Workspace/cucumberframework/Feature/login.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
